// <auto-generated />
using ApiRotina.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRotina.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiRotina.Models.Dieta", b =>
                {
                    b.Property<int>("IdDieta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDieta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDieta"));

                    b.Property<string>("Alimentos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DietaClass")
                        .HasColumnType("int");

                    b.Property<string>("Nutrientes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Refeicoes")
                        .HasColumnType("int");

                    b.HasKey("IdDieta");

                    b.ToTable("TB_DIETAS");

                    b.HasData(
                        new
                        {
                            IdDieta = 1,
                            Alimentos = " Refeição 1:Ovos mexidos (6 claras e 2 gemas), Aveia (50g) e Banana (1 unidade), Refeição 2: Peito de frango grelhado (150g)Arroz integral (100g)Brócolis cozido (100g), Refeição 3 (pré-treino):Batata doce (150g), Peito de frango grelhado (150g), Salada de folhas verdes (alface, rúcula, espinafre) com azeite de oliva, Refeição 4 (pós-treino):Whey protein (30g) com águaBanana (1 unidade).",
                            Dia = "Domingo",
                            DietaClass = 1,
                            Nutrientes = "Proteína: 180g, Carboidratos: 177g, Gordura: 20g e Fibras: 21g",
                            Refeicoes = 4
                        },
                        new
                        {
                            IdDieta = 2,
                            Alimentos = "Refeição 1: 2 ovos cozidos, 1 xícara de leite, 1 fatia de pão integral, 1 banana, Refeição 2: 100 g de frango grelhado, 200 g de arroz integral, 100 g de legumes cozidos, Refeição 3: 150 g de iogurte natural, 100 g de frutas, Refeição 4: 200 g de peixe grelhado, 300 g de batata doce assada, 100 g de legumes cozidos.",
                            Dia = "Segunda",
                            DietaClass = 2,
                            Nutrientes = "200 g de Proteína, 350 g de Carboidratos, 80 g de Gorduras",
                            Refeicoes = 4
                        },
                        new
                        {
                            IdDieta = 3,
                            Alimentos = "Refeição 1: 1 xícara de mingau de aveia com frutas e castanhas, Refeição 2: 200 g de carne moída magra, 250 g de macarrão integral, 100 g de legumes cozidos, Refeição 3: 100 g de pão integral com pasta de amendoim, Refeição 4: 150 g de frango desfiado, 300 g de batata inglesa cozida, 100 g de legumes cozidos.",
                            Dia = "Terça",
                            DietaClass = 3,
                            Nutrientes = "200 g de Proteína, 350 g de Carboidratos, 80 g de Gorduras",
                            Refeicoes = 4
                        },
                        new
                        {
                            IdDieta = 4,
                            Alimentos = " Refeição 1:Ovos mexidos (6 claras e 2 gemas), Aveia (50g) e Banana (1 unidade), Refeição 2: Peito de frango grelhado (150g)Arroz integral (100g)Brócolis cozido (100g), Refeição 3 (pré-treino):Batata doce (150g), Peito de frango grelhado (150g), Salada de folhas verdes (alface, rúcula, espinafre) com azeite de oliva, Refeição 4 (pós-treino):Whey protein (30g) com águaBanana (1 unidade).",
                            Dia = "Quarta",
                            DietaClass = 4,
                            Nutrientes = "Proteína: 180g, Carboidratos: 177g, Gordura: 20g e Fibras: 21g",
                            Refeicoes = 4
                        },
                        new
                        {
                            IdDieta = 5,
                            Alimentos = "Refeição 1: 2 ovos cozidos, 1 xícara de leite, 1 fatia de pão integral, 1 banana, Refeição 2: 100 g de frango grelhado, 200 g de arroz integral, 100 g de legumes cozidos, Refeição 3: 150 g de iogurte natural, 100 g de frutas, Refeição 4: 200 g de peixe grelhado, 300 g de batata doce assada, 100 g de legumes cozidos.",
                            Dia = "Quinta",
                            DietaClass = 5,
                            Nutrientes = "200 g de Proteína, 350 g de Carboidratos, 80 g de Gorduras",
                            Refeicoes = 4
                        },
                        new
                        {
                            IdDieta = 6,
                            Alimentos = "Refeição 1: 1 xícara de mingau de aveia com frutas e castanhas, Refeição 2: 200 g de carne moída magra, 250 g de macarrão integral, 100 g de legumes cozidos, Refeição 3: 100 g de pão integral com pasta de amendoim, Refeição 4: 150 g de frango desfiado, 300 g de batata inglesa cozida, 100 g de legumes cozidos.",
                            Dia = "Sexta",
                            DietaClass = 6,
                            Nutrientes = "200 g de Proteína, 350 g de Carboidratos, 80 g de Gorduras",
                            Refeicoes = 4
                        },
                        new
                        {
                            IdDieta = 7,
                            Alimentos = "Refeição 1:Ovos mexidos (6 claras e 2 gemas), Aveia (50g) e Banana (1 unidade), Refeição 2: Peito de frango grelhado (150g)Arroz integral (100g)Brócolis cozido (100g), Refeição 3 (pré-treino):Batata doce (150g), Peito de frango grelhado (150g), Salada de folhas verdes (alface, rúcula, espinafre) com azeite de oliva, Refeição 4 (pós-treino):Whey protein (30g) com águaBanana (1 unidade).",
                            Dia = "Sabado",
                            DietaClass = 7,
                            Nutrientes = "Proteína: 180g, Carboidratos: 177g, Gordura: 20g e Fibras: 21g",
                            Refeicoes = 4
                        });
                });

            modelBuilder.Entity("ApiRotina.Models.Treino", b =>
                {
                    b.Property<int>("IdTreino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTreino");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTreino"));

                    b.Property<string>("Exercicios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TreinoClass")
                        .HasColumnType("int");

                    b.HasKey("IdTreino");

                    b.ToTable("TB_TREINOS");

                    b.HasData(
                        new
                        {
                            IdTreino = 1,
                            Exercicios = "Supino reto com halteres: 3 séries de 8-12 repetições, Rosca bíceps com halteres: 3 séries de 8-12 repetições, Agachamento com barra: 3 séries de 8-12 repetições, Leg press: 3 séries de 10-15 repetições, Remada curvada com halteres: 3 séries de 8-12 repetições, Tríceps francês com halteres: 3 séries de 8-12 repetições.",
                            TreinoClass = 1
                        },
                        new
                        {
                            IdTreino = 2,
                            Exercicios = "Agachamento com barra: 3 séries de 8-12 repetições, Leg press: 3 séries de 10-15 repetições, Leg extension: 3 séries de 10-15 repetições, Legcurl:3 séries de 10-15 repetições.",
                            TreinoClass = 2
                        },
                        new
                        {
                            IdTreino = 3,
                            Exercicios = "Elevação de panturrilha em pé: 3 séries de 15-20 repetições, Elevação de panturrilha sentado: 3 séries de 15-20 repetições, Elevação de panturrilha unilateral: 3 séries de 15-20 repetições para cada perna.",
                            TreinoClass = 3
                        },
                        new
                        {
                            IdTreino = 4,
                            Exercicios = "Rosca direta com halteres: 3 séries de 8-12 repetições, Rosca martelo com halteres: 3 séries de 8-12 repetições, Rosca concentrada com halteres: 3 séries de 8-12 repetições, Tríceps francês com halteres: 3 séries de 8-12 repetições, Tríceps pushdown: 3 séries de 10-15 repetições.",
                            TreinoClass = 4
                        },
                        new
                        {
                            IdTreino = 5,
                            Exercicios = "Agachamento com barra: 3 séries de 8-12 repetições, Leg press: 3 séries de 10-15 repetições, Leg extension: 3 séries de 10-15 repetições, Legcurl:3 séries de 10-15 repetições.",
                            TreinoClass = 5
                        },
                        new
                        {
                            IdTreino = 6,
                            Exercicios = "Supino reto com halteres: 3 séries de 8-12 repetições, Rosca bíceps com halteres: 3 séries de 8-12 repetições, Agachamento com barra: 3 séries de 8-12 repetições, Leg press: 3 séries de 10-15 repetições, Remada curvada com halteres: 3 séries de 8-12 repetições, Tríceps francês com halteres: 3 séries de 8-12 repetições.",
                            TreinoClass = 6
                        },
                        new
                        {
                            IdTreino = 7,
                            Exercicios = "Elevação de panturrilha em pé: 3 séries de 15-20 repetições, Elevação de panturrilha sentado: 3 séries de 15-20 repetições, Elevação de panturrilha unilateral: 3 séries de 15-20 repetições para cada perna.",
                            TreinoClass = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
